-- 1. Create the Table Schema
CREATE TABLE IF NOT EXISTS shopping_trends (
    customer_id INT PRIMARY KEY,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(50),
    category VARCHAR(50),
    purchase_amount_usd FLOAT,
    location VARCHAR(50),
    size VARCHAR(10),
    color VARCHAR(20),
    season VARCHAR(20),
    review_rating FLOAT,
    subscription_status VARCHAR(10),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    promo_code_used VARCHAR(10),
    previous_purchases INT,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50)
);

-- Q1. Total revenue generated by male vs. female customers
SELECT 
    gender, 
    SUM(purchase_amount) AS total_revenue
FROM shopping_trends
GROUP BY gender
ORDER BY total_revenue DESC;

-- Q2. Customers who used a discount but still spent more than the average
SELECT * FROM shopping_trends
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM shopping_trends);

-- Q3. Top 5 products with the highest average review rating
SELECT item_purchased, 
       ROUND(AVG(review_rating)::numeric, 2) AS avg_rating
FROM shopping_trends
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Average Purchase Amounts: Standard vs. Express Shipping
SELECT shipping_type, 
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend
FROM shopping_trends
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Subscriber vs Non-Subscriber: Average spend and total revenue
SELECT subscription_status, 
       COUNT(*) AS total_customers,
       ROUND(AVG(purchase_amount)::numeric, 2) AS avg_spend, 
       SUM(purchase_amount) AS total_revenue
FROM shopping_trends
GROUP BY subscription_status;

-- Q6. Top 5 products with the highest percentage of discounted purchases
SELECT item_purchased, 
       ROUND((100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*))::numeric, 2) AS discount_percentage
FROM shopping_trends
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Customer Segmentation: New, Returning, and Loyal
SELECT 
    CASE 
        WHEN previous_purchases <= 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM shopping_trends
GROUP BY customer_segment;

-- Q8. Top 3 most purchased products within each category
SELECT category, item_purchased, purchase_count
FROM (
    SELECT category, 
           item_purchased, 
           COUNT(*) AS purchase_count,
           RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM shopping_trends
    GROUP BY category, item_purchased
) ranked_products
WHERE rnk <= 3;

-- Q9. Subscription likelihood for repeat buyers (> 5 purchases)
SELECT 
    CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Occasional Buyer' END AS buyer_type,
    subscription_status,
    COUNT(*) AS count
FROM shopping_trends
GROUP BY buyer_type, subscription_status
ORDER BY buyer_type, count DESC;

-- Q10. Revenue contribution of each age group
-- Note: This uses the 'age_group' column you created in Pandas
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM shopping_trends
GROUP BY age_group
ORDER BY total_revenue DESC;